src/Entity/Todo.php
<?php

namespace App\Entity;

use App\Repository\TodoRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TodoRepository::class)
 */
class Todo
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $category;

    /**
     * @ORM\Column(type="integer")
     */
    private $priority;

    /**
     * @ORM\Column(type="date")
     */
    private $due_date;

    /**
     * @ORM\ManyToOne(targetEntity=Tag::class, inversedBy="todos")
     * @ORM\JoinColumn(nullable=false)
     */
    private $tag;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(string $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getPriority(): ?int
    {
        return $this->priority;
    }

    public function setPriority(int $priority): self
    {
        $this->priority = $priority;

        return $this;
    }

    public function getDueDate(): ?\DateTimeInterface
    {
        return $this->due_date;
    }

    public function setDueDate(\DateTimeInterface $due_date): self
    {
        $this->due_date = $due_date;

        return $this;
    }

    public function getTag(): ?Tag
    {
        return $this->tag;
    }

    public function setTag(?Tag $tag): self
    {
        $this->tag = $tag;

        return $this;
    }
}

src/Form/TodoType.php
<?php

namespace App\Form;

use App\Entity\Todo;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TodoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('tag')
            ->add('name',TextType::class)
            ->add('description',TextType::class)
            ->add('category',TextareaType::class)
            ->add('priority',ChoiceType::class,
            ['choices'=> [
                '1'=>"1",
                '2'=>"2",
                '3'=>"3",
                ],
            ])
            ->add('due_date',DateType::class, ['widget'=>'single_text'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Todo::class,
        ]);
    }
}

src/Controller/TodoController.php
<?php

namespace App\Controller;

use App\Entity\Todo;
use App\Form\TodoType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class TodoController extends AbstractController
{
    /**
     * @Route("/todo/search", name="search_todo",methods={"GET"})
     */
    public function searchTodo(Request $request) : Response{
        $searchText = $request->query->get('searchText');
        
        // Search all todos by TodoName or categoryName
        // Call Doctrine
        $doctrine = $this->getDoctrine();
        $todoRepos = $doctrine->getRepository(Todo::class);
        
        $todos = $todoRepos->searchByTodoNameOrCategoryName($searchText);
        
        return $this->render("todo/search.html.twig",[
            'todos' => $todos
        ]);
    }
    
    /**
     * @Route("/todo",name="todo_list")
     */
    public function listAction() {
        // Call Doctrine
        $doctrine = $this->getDoctrine();
        $todoRepos = $doctrine->getRepository(Todo::class);
        
        $todos = $todoRepos->findAll();
        return $this->render('todo/index.html.twig',['todos'=>$todos]);
    }
    


    /**
     * @Route("/todo/details/{id}",name="todo_details")
     */
    public function detailsAction($id) {
        $todos = $this->getDoctrine()
            ->getRepository(Todo::class)
            ->find($id);
        return $this->render('todo/details.html.twig',['todos'=>$todos]);
    }

    /**
     * @Route("/todo/delete/{id}",name="todo_delete")
     */
    public function deleteAction($id) {
        $em = $this->getDoctrine()->getManager();
        $todo = $em->getRepository(Todo::class)->find($id);
        $em->remove($todo);
        $em->flush();

        $this->addFlash('error','Todo deleted');
        return $this->redirectToRoute('todo_list');
    }

    /**
     * @Route("/todo/create", name="todo_create", methods={"GET","POST"})
     */
    public function createAction(Request $request)
    {
        $todo = new Todo();
        $form = $this->createForm(TodoType::class, $todo);

        if ($this->saveChanges($form, $request, $todo)) {
            $this->addFlash(
                'notice',
                'Todo Added'
            );

            return $this->redirectToRoute('todo_list');
        }

        return $this->render('todo/create.html.twig', [
            'form' => $form->createView()
        ]);
    }

    public function saveChanges($form, $request, $todo)
    {
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $todo->setName($request->request->get('todo')['name']);
            $todo->setCategory($request->request->get('todo')['category']);
            $todo->setDescription($request->request->get('todo')['description']);
            $todo->setPriority($request->request->get('todo')['priority']);
            $todo->setDueDate(\DateTime::createFromFormat('Y-m-d', $request->request->get('todo')['due_date']));
            $em = $this->getDoctrine()->getManager();
            $em->persist($todo);
            $em->flush();

            return true;
        }
        return false;
    }

    /**
     * @Route("/todo/edit/{id}", name="todo_edit")
     */
    public function editAction($id, Request $request) {
        $em = $this->getDoctrine()->getManager();
        $todo = $em->getRepository(Todo::class)->find($id);
        $form = $this->createForm(TodoType::class,$todo);

        if ($this->saveChanges($form, $request, $todo)) {
            $this->addFlash('notice', "Todo Edited");
            return $this->redirectToRoute('todo_list');
        }

        return $this->render('todo/edit.html.twig', ['form'=>$form->createView()]);
    }
}

templates/todo/create.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    {{ form_start(form) }}
    <div class="form-group">
        <label for="name">Name:</label>
        {{ form_widget(form.name,{
            'attr':{
                'class':'form-control',
                'placeholder': 'Task name'
            }
        }) }}
        <div class="invalid-feedback">
            {{ form_errors(form.name) }}
        </div>
    </div>
    <div class="form-group">
        <label for="category">Category:</label>
        {{ form_widget(form.category,{
            'attr':{
                'class':'form-control',
                'placeholder': 'Category name'
            }
        }) }}
    </div>
    <div class="form-group">
        <label for="description">Description:</label>
        {{ form_widget(form.description,{
            'attr':{
                'class':'form-control',
                'placeholder': 'Description'
            }
        }) }}
    </div>
    <div class="form-group">
        <label for="priority">Priority:</label>
        {{ form_widget(form.priority,{
            'attr':{
                'class':'form-control'
            }
        }) }}
    </div>
    <div class="form-group">
        <label for="priority">Tag:</label>
        {{ form_widget(form.tag,{
            'attr':{
                'class':'form-control'
            }
        }) }}
    </div>
    <div class="form-group">
        <label for="due_date">Due Date</label>
        {{ form_widget(form.due_date,{
            'attr':{
                'class':'form-control'
            }
        }) }}
    </div>
    <input type="submit" name="create_todo" value="Create" class="btn btn-primary"/>
    {{ form_end(form) }}
{% endblock %}

templates/todo/details.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <a href="{{ path('todo_list') }}" class="btn btn-default">Back to Todo List</a>
    <hr/>
    <h2 class="page-header">{{ todos.name }}</h2>
    <ul class="list-group">
        <li class="list-group-item">Category: {{ todos.category }}</li>
        <li class="list-group-item">Priority: {{ todos.priority }}</li>
        <li class="list-group-item">Tag: {{ todos.tag.description }}</li>
        <li class="list-group-item">Due: <strong>{{ todos.dueDate|date('F j,Y, g:i a') }}</strong></li>
    </ul>
    <p>{{ todos.description }}</p>
{% endblock %}

templates/todo/edit.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    {{ form_start(form) }}
    <div class="form-group">
        <label for="name">Name:</label>
        {{ form_widget(form.name,{
            'attr':{
                'class':'form-control',
                'placeholder': 'Task name'
            }
        }) }}
    </div>
    <div class="form-group">
        <label for="category">Category:</label>
        {{ form_widget(form.category,{
            'attr':{
                'class':'form-control',
                'placeholder': 'Category name'
            }
        }) }}
    </div>
    <div class="form-group">
        <label for="description">Description:</label>
        {{ form_widget(form.description,{
            'attr':{
                'class':'form-control',
                'placeholder': 'Description'
            }
        }) }}
    </div>
    <div class="form-group">
        <label for="priority">Priority:</label>
        {{ form_widget(form.priority,{
            'attr':{
                'class':'form-control'
            }
        }) }}
    </div>
    <div class="form-group">
        <label for="due_date">Due Date</label>
        {{ form_widget(form.due_date,{
            'attr':{
                'class':'form-control'
            }
        }) }}
    </div>
    <input type="submit" name="edit_todo" value="Edit" class="btn btn-primary"/>
    {{ form_end(form) }}
{% endblock %}

templates/todo/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="bs-example" data-example-id="striped-table">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>Todo</th>
                <th>Due date</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for todo in todos %}
                <tr>
                    <th scope="row">{{ todo.id }}</th>
                    <td>{{ todo.name }}</td>
                    <td>{{ todo.dueDate|date('F j,Y, g:i a') }}</td>
                    <td>
                        {#<a href="{{ path('todo_details', {'id': todo.id}) }} " class='btn btn-success'>View</a>#}
                        {#<a href="{{ path('todo_edit', {'id': todo.id}) }}" class='btn btn-default'>Edit</a>#}
                        {#<a href="{{ path('todo_delete', {'id': todo.id}) }}" class='btn btn-danger'>Delete</a>#}
                        <a href="{{ path ('todo_details', {'id':todo.id}) }}" class='btn btn-success'>View</a>
                        <a href="{{ path('todo_edit', {'id': todo.id}) }}" class='btn btn-default'>Edit</a>
                        <a href="{{ path ('todo_delete', {'id':todo.id}) }}" class='btn btn-danger'>Delete</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

templates/todo/search.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <form method="get" action={{ path('search_todo')}} >
        <div class="mb-3">
            <input type="text" class="form-control" id="searchText" name="searchText"
                   placeholder="Search by Todo name or Category Name"
            >
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Search</button>

        </div>
    </form>
    <div class="bs-example" data-example-id="striped-table">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>Todo</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for todo in todos %}
                <tr>
                    <th scope="row">{{ todo.id }}</th>
                    <td>{{ todo.name }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}